spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cycy?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.fruit.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  file:
    path: C:\project\IworkSpace\fruit

server:
  port: 8989
